### ISSUE TITLE
circular dependency

### ISSUE THREAD

**Issue by tomasSimandl** [pornosaur/operating-system-simulation#39]
In Issue #28 was created circular dependency. Solution was create new file **VfsStructures.h** which contains `struct super_block` and `struct dentry`. Problem is that `dentry` point to **FS** and **FS** use `dentry` _(new circular dependency)_. I remove include `"FS.h"` in **VfsStructures** and add new line `class FS;` to say compiler that **FS** is class and will be define in a future. This solution works but i am not sure if its ok.

**Comment by patpatera** [comment]
yesp, that is the usual approach

**Comment by patpatera** [comment]
Btw. it is known as forward decleration if you wanna find out something more about that

**Comment by patpatera** [comment]
Btw2. if you use that, you will have to use the class, in your next code, only as pointer or reference because compiler doesnt know any details about class, especially about `sizeof(class)` to allocate a static memory.

**Comment by tomasSimandl** [comment]
yes, I assumed that. I used it only as a pointer in `struct dentry`.
