### ISSUE TITLE
offset in Handler methods read and write

### ISSUE THREAD

**Issue by tomasSimandl** [pornosaur/operating-system-simulation#42]
For **offset** setting there should be method `fseek`. If you want to have **offset** in `read ` and `write` you must add constant which are defined in **api.h** `fsBegining`, `fsCurrent`, `fsEnd`.

I think that better is move `unsigned long position` from `fileHandler` to `Handler` and use methods `fseek` and `ftell`

**Comment by kanakl** [comment]
I think  it could be in Handler.

**Comment by patpatera** [comment]
Yea, it should be there.

**Comment by patpatera** [comment]
Will you do that @tomasSimandl ?

**Comment by tomasSimandl** [comment]
Yes I will do that
