### ISSUE TITLE
Implement Console (Input, Output)

### ISSUE THREAD

**Issue by patpatera** [pornosaur/operating-system-simulation#5]
* Nastudovat implementaci z CW.
* Implementovat stejne reseni v Kernelu.

**Comment by kanakl** [comment]
What return when ctrl+z is pressed?

**Comment by patpatera** [comment]
Return function read as false and set read = 0 => this is the way how to recognize EOF

**Comment by kanakl** [comment]
Ok, I see it but now I found another problem. When I press CTRL+Z than mStdInOpen is closed and I cant read anymore.It is problem, when I stop rgen with ctrl+z and I want read next command.

**Comment by kanakl** [comment]
TODO: closing
