### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tomasSimandl** [pornosaur/operating-system-simulation#80]
when is called Create_Process 

- [x]  memory leak with **name of command** (`kiv_os_str::copy_string(cmd.command)`)
- [x] memory leak **command arguments**. Now are arguments deleted in commands but when is called not existing command -> memory leak. _I think -> delete free in commands -> call free in CommandWrapper_
- [x] memory leak in wc. Must free out -> const char *output = kiv_os_str::copy_string(out); 
- [x] memory leak in wc. Must free input -> char *input = (char *)malloc(1024 * sizeof(char));
- [x] memory leak in cd. Buffer char *buffer = (char*)malloc(sizeof(char) * buffer_size); (line 139) is free only once in if, but nowhere else.

**Comment by kanakl** [comment]
I fix it.

**Comment by kanakl** [comment]
I need command arguments, which are saved in tsi. When call free in CommandWrapper, it couldn't used in created processes. I call free in processes after end of program(commands) so free in commands is unnecessary.

**Comment by patpatera** [comment]
* Fixed, you can check it
