### ISSUE TITLE
Command parser - incorect parsing

### ISSUE THREAD

**Issue by kanakl** [pornosaur/operating-system-simulation#85]
Command echo _aaa > aaa.txt_ is ok, but command _rgen > aaa.txt_ show in shell incorect syntax 
![image](https://user-images.githubusercontent.com/17461492/32995249-249a5180-cd72-11e7-9a8e-473917c2c422.png)

**Comment by kanakl** [comment]
Command wc < aaa.txt is the same problem

**Comment by patpatera** [comment]
* There is still some bugs...

**Comment by patpatera** [comment]
* Completed
