### ISSUE TITLE
Interruption question

### ISSUE THREAD

**Issue by patpatera** [pornosaur/operating-system-simulation#9]
## Can I allow to interruption while reading a file? ##
Leave a comments below

**Comment by patpatera** [comment]
I think we have to allow to interruption because interruption it is only about find a right routine in table of interruption such as vector and let a process works but with allowed interruption.

**Comment by tomasSimandl** [comment]
In interruption should be only the base operations. As you said only find a right routine and add routine to the "scheduler" I thin in our solution it will be like mutex above table of interruption.

**Comment by patpatera** [comment]
Yep, it has already implemented by binary semaphore as you can se in `function Sys_Call`. There is semaphore because I was talking with Pesicka and he said you should lock kernel at the beginning of sys call but you could allow to interruption anywhere in process if it has already completed necessary operation under the kernel. So I am not sure if you could use mutex because mutex can be unlocked only by process which locked it.
